// client/PersonalFinances.Client/src/features/common/footer/components/Footer.tsx
import styles from './Footer.module.scss';

export const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className={styles['footer']}>
      <div className={styles['footer__content']}>
        <p className={styles['footer__text']}>
          &copy; {currentYear} nankoviliya. All Rights Reserved.
        </p>
        <div className={styles['footer__links']}>
          <a
            href="https://google.com"
            target="_blank"
            rel="noopener noreferrer"
            className={styles['footer__link']}
          >
            Portfolio
            <i className="pi pi-external-link"></i>
          </a>
          <a
            href="https://github.com/nankoviliya"
            target="_blank"
            rel="noopener noreferrer"
            className={styles['footer__link']}
          >
            GitHub
            <i className="pi pi-github"></i>
          </a>
          <a
            href="https://www.linkedin.com/in/iliya-nankov/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles['footer__link']}
          >
            LinkedIn
            <i className="pi pi-linkedin"></i>
          </a>
        </div>
      </div>
    </footer>
  );
};

// src/frontend/life-sync-angular-client/src/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  protected currentYear: number = new Date().getFullYear();
}

<footer class="footer">
  <div class="footer__content">
    <p class="footer__text">
      &copy; {{ currentYear }} nankoviliya. All Rights Reserved.
    </p>
    <div class="footer__links">
      <a
        href="https://google.com"
        target="_blank"
        rel="noopener noreferrer"
        class="footer__link"
      >
        Portfolio
        <i class="pi pi-external-link"></i>
      </a>
      <a
        href="https://github.com/nankoviliya"
        target="_blank"
        rel="noopener noreferrer"
        class="footer__link"
      >
        GitHub
        <i class="pi pi-github"></i>
      </a>
      <a
        href="https://www.linkedin.com/in/iliya-nankov/"
        target="_blank"
        rel="noopener noreferrer"
        class="footer__link"
      >
        LinkedIn
        <i class="pi pi-linkedin"></i>
      </a>
    </div>
  </div>
</footer>
